theme: jekyll-theme-minimal

title: Bastiaan Boland
description: Econometrician interested in IT.

logo: assets/images/fotoBastiaanBoland.jpg
show_downloads: false

plugins:
  - jekyll-relative-links

