remote_theme: pages-themes/minimal@v0.2.0

title: Bastiaan Boland
description: Computers, math, mind.

logo: assets/images/fotoBastiaanBoland.png
show_downloads: false

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

