theme: jekyll-theme-minimal

title: Bastiaan Boland
description: Computer nerd by heart, econometrician by trade.

logo: assets/images/fotoBastiaanBoland.jpg
show_downloads: false

plugins:
  - jekyll-relative-links

