theme: jekyll-theme-minimal

title: Bastiaan Boland
description: Econometrist met interesse voor IT.

logo: img/BastiaanBolandLinkedIn.jpg
show_downloads: false

plugins:
  - jekyll-relative-links

defaults:
  -
    scope:
      path: "attractors"
    values:
      layout: "attractor"
