remote_theme: pages-themes/minimal@v0.2.0

title: Bastiaan Boland
author: Bastiaan Boland

logo: assets/images/fotoBastiaanBoland.png
show_downloads: false

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-furigana


defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"


