theme: jekyll-theme-minimal

title: Bastiaan Boland
description: Econometrician interested in IT.

logo: assets/images/BastiaanBolandLinkedIn.jpg
show_downloads: false

plugins:
  - jekyll-relative-links

defaults:
  -
    scope:
      path: "attractors"
    values:
      layout: "attractor"
